apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vlang
  template:
    metadata:
      labels:
        app: vlang
    spec:
      containers:
      - name: vlang
        image: docker.io/up1ps/vlang:latest
        ports:
        - containerPort: 4000
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: vlang
spec:
  type: NodePort
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30002
    name: vlang
  selector:
    app: vlang
