apiVersion: apps/v1
kind: Deployment
metadata:
  name: vrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vrest
  template:
    metadata:
      labels:
        app: vrest
    spec:
      containers:
      - name: vrest
        image: docker.io/up1ps/vrest:latest
        ports:
        - containerPort: 4003
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: vrest
spec:
  type: NodePort
  ports:
  - port: 4003
    targetPort: 4003
    nodePort: 30003
    name: vrest
  selector:
    app: vrest
